### ISSUE TITLE
[Bug]: Invalid json snapshot

### ISSUE THREAD

**Issue by KoNekoD** [gkampitakis/go-snaps#111]
### Description

![image](https://github.com/user-attachments/assets/3ab7c9dc-5410-4049-af2a-d01ec91abeed)

### Steps to Reproduce

Create json snappshot

### Expected Behavior

Without invalid characters, only json  file

**Comment by KoNekoD** [comment]
Just
```
{
...
}
```

**Comment by gkampitakis** [comment]
Hi, thanks for opening this issue. This is expected behaviour, of how go-snaps works and not a bug. It's similar to how jest is storing multiple snapshots in a file. 

If you want to save your snapshot in a single file as a json you could do 


```go
snaps.WithConfig(snaps.Ext(".json")).
    MatchStandaloneSnapshot(t, "{}")
```

This will create a single file with json extension with your data.

**Comment by KoNekoD** [comment]
I want to be able to immediately structure this method to read

**Comment by KoNekoD** [comment]
Everything in your library would be perfect if you didn't have those fucking square brackets that turn the file red. I tried to refactor it, but the cat's overcomplicated.

**Comment by gkampitakis** [comment]
You could do it on your tests instead of creating a short name for every simple configuration option.

```
jsonSnapshot := snaps.WithConfig(snaps.Ext(".json")).MatchStandaloneSnapshot

....

jsonSnapshot(t, "{}")
```
and then reuse it wherver you want.

**Comment by gkampitakis** [comment]
> Everything in your library would be perfect if you didn't have those fucking square brackets that turn the file red. I tried to refactor it, but the code overcomplicated.

Sorry for this but this library might not be for you then. You can use https://github.com/bradleyjkemp/cupaloy that does this by default.

**Comment by gkampitakis** [comment]
Closing this as this is expected behaviour. Feel free to open another issue if you need some help.
