### ISSUE TITLE
Behaviour changed? Secrets now redacted?

### ISSUE THREAD

**Issue by markussiebert** [gkampitakis/go-snaps#28]
Hi,

did you changed something regarding secret values? My tests change from

```
[Test_UpdateSecret - 1]
>>>SecretsManagerMockClient.PutSecretValue.Input
{
  ClientRequestToken: "4547532a137611d83958d17095c6c2d38ae0036a760c3b79c9dd5957d1c20cf2",
  SecretId: "arn:${Partition}:secretsmanager:${Region}:${Account}:secret:${SecretId}",
  SecretString: "some-secret-data"
}
```

to 

```
[Test_UpdateSecret - 1]
>>>SecretsManagerMockClient.PutSecretValue.Input
{
  ClientRequestToken: "4547532a137611d83958d17095c6c2d38ae0036a760c3b79c9dd5957d1c20cf2",
  SecretId: "arn::secretsmanager:::secret:",
  SecretString: <sensitive>
}
```

Can I disable the replacing with <sensitive>? I think no one stores real secrets in tests...

**Comment by gkampitakis** [comment]
Hey :wave:, no I have not changed anything in the library regarding secrets. The library doesn't have any idea of what data are stored in the snaps. The only change was around escaping `---` those "special characters".

**Comment by markussiebert** [comment]
Thank you a lot :-)
