### ISSUE TITLE
[Bug]: Cryptic error message for snaps saved using "CRLF" instead of "LF" line ending

### ISSUE THREAD

**Issue by JBongars** [gkampitakis/go-snaps#63]
### Description

Pulling the snaps on a Windows and running the tests on a Docker (Linux) environment produces the following error:-

```bash
--- FAIL: TestFoo (0.01s)
  --- FAIL: TestFoo/test_snapshot (0.01s)
      foo_test.go:34: snapshot not found
```

This error is cryptic because suggests that the file doesn't exist when it is actually the wrong format. This can happen when developer clones a repository from Github and attempts to run the tests in a Docker container.

### Steps to Reproduce

1. Go to __snapshot__ folder.
2. Select a snap
3. Change the line ending from LF to CRLF on a Windows machine
4. Attempt to run the tests in a Docker container or some kind of Linux environement

### Expected Behavior

Proposal: Update the docs to highlight this issue and maybe change the error message to be less cryptic. i.e.

```bash
--- FAIL: TestFoo (0.01s)
  --- FAIL: TestFoo/test_snapshot (0.01s)
      foo_test.go:34: snapshot not found or wrong format
```

Proposed changes to docs under notes. (Tried to create a PR but my branch was not accepted):

```md
5. If you are running this package on both a Windows and Linux environment, you may encounter the following error:-

\```bash
--- FAIL: TestFoo (0.01s)
  --- FAIL: TestFoo/test_snapshot (0.01s)
      foo_test.go:34: snapshot not found
\```

this is because the snapshots are saved with a different line ending on each platform (LF on Linux, CRLF on Windows). To fix this, you can use the [dos2unix](https://pkgs.alpinelinux.org/package/edge/community/x86/dos2unix) tool to convert the line endings to LF on Linux
```

**Comment by JBongars** [comment]
@gkampitakis just saw the new release, thanks for fixing this issue :)

**Comment by gkampitakis** [comment]
Thanks for reporting the issue. Looks like my handwritten regex could not handle CRLF so it was not able to find snasphots inside the file and was reporting `snapshot not found or wrong format`. Tell me if now works for you 😄
