### ISSUE TITLE
[Feature Request]: Expose ability to update snapshot via the API

### ISSUE THREAD

**Issue by wagoodman** [gkampitakis/go-snaps#77]
### 🚀 Feature Proposal

It would be great to be able to update snapshots more programmatically:
```golang
	cfg := snaps.WithConfig(snaps.Update(true))
	cfg.MatchSnapshot(t, myTestSubject)
```

In this way you could have other test conditions / mechanisms that enforce when a snapshot can and should be updated.

### Motivation

Today we use the `flag` package which hooks nicely into the standard test utils:

```golang
package spdxjson

import (
	"flag"
	"testing"
)

var updateSnapshot = flag.Bool("update-spdx-json-snapshot", false, "update the *.golden files for spdx-json encoders")

func Test_Something(t *testing.T) {
	...
	if *updateSnapshot {
		// do something...
	}
	...
}
``` 

Which can be used like so:
```
go test ./path/to/package -update-spdx-json-snapshot
```

See:
- https://github.com/anchore/syft/blob/44e54802380f949a1476c25c1b48c5e3488e89bc/syft/formats/internal/testutils/snapshot.go#L45-L63
- https://github.com/anchore/syft/blob/44e54802380f949a1476c25c1b48c5e3488e89bc/syft/formats/spdxjson/encoder_test.go#L10

This has the nice quality that:
- just by running tests as usual you cannot write out a snapshot
- you can continually update a snapshot without needing to scope the `go test` command with the correct env var while developing on a narrow feature that isn't stable yet

### Example

Combining the motivation and the feature request:

```golang
package spdxjson

import (
	"flag"
	"testing"
)

var updateSnapshot = flag.Bool("update-spdx-json-snapshot", false, "update the *.golden files for spdx-json encoders")

func Test_Something(t *testing.T) {
	...
	cfg := snaps.WithConfig(snaps.Update(*updateSnapshot))
	cfg.MatchSnapshot(t, myTestSubject)
	...
}
``` 

In which case the flags are the only way to update snapshot files.

**Comment by gkampitakis** [comment]
hey 👋  thanks a lot for opening this issue. I really like this idea. I created a draft pr to support this. I am thinking that the priority should be `CI` >  `snaps.Update`  > `UPDATE_SNAPS` . So if running on a CI the snaps won't update and will fail. wdyt ?

**Comment by gkampitakis** [comment]
Have added this on #78 please tell me if that works for you. Again thanks for opening this issue.
