### ISSUE TITLE
[Feature Request]: Add docs on path syntax

### ISSUE THREAD

**Issue by mrsufgi** [gkampitakis/go-snaps#83]
### 🚀 Feature Proposal

Add docs on path syntax.

It took me some time to figure out the JSON path structure for matchers. 

I ended up finding: 
https://pkg.go.dev/github.com/tidwall/gjson@v1.17.0#readme-path-syntax

Which is the package used for handling JSON paths here.

A referral to the docs would be an excellent addition.

<3

**Comment by gkampitakis** [comment]
Hey 👋  Thanks a lot for opening this issue. I am sorry for this, I thought I have linked it already on the docs.
